default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

env: &env
  host: localhost
  database: lunchDelievery
  username: myuser
  password: 'mypass'

development: &development
  <<: *default
  <<: *env

test:
  <<: *default
  <<: *env
  database: lunchDelieveryTest
  timeout: 10000
  pool: 10